.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
      changes:
        - "*.js"
        - "*.ts"
        - "*.json"
        - "Dockerfile"
        - "commands/**/*"
    - if: $CI_DEFAULT_BRANCH != $CI_COMMIT_BRANCH
      when: manual
stages:
  - build
  - deploy
variables:
  IMAGE_REPO: $REGISTRY_USER/$CI_PROJECT_NAME
  IMAGE_TAG: $REGISTRY/$REGISTRY_USER/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $REGISTRY/$REGISTRY_USER/$CI_PROJECT_NAME:latest
  IMAGE_CACHE: $REGISTRY/$REGISTRY_USER/$CI_PROJECT_NAME:buildcache
  FF_USE_FASTZIP: "true"
  DOCKER_BUILDKIT: "1"
  BUILDKIT_INLINE_CACHE: "1"

build:
  stage: build
  image: 
    name: moby/buildkit:buildx-stable-1-rootless
    entrypoint: [""]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  rules:
    - !reference [.default_rules, rules]
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASS\"}}}" > ~/.docker/config.json
  script:
    - |
      buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=Dockerfile \
        --export-cache type=registry,ref=$IMAGE_CACHE,mode=max,compression=zstd,oci-mediatypes=true \
        --import-cache type=registry,ref=$IMAGE_CACHE \
        --output type=image,name=$IMAGE_TAG,push=true,compression=zstd,oci-mediatypes=true \
        --output type=image,name=$IMAGE_LATEST,push=true,compression=zstd,oci-mediatypes=true
  allow_failure: false


deploy:
  stage: deploy
  image: vuongprogk/deploy:v1-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH 
      changes:
        - "*.js"
        - "*.ts"
        - "*.json"
        - "Dockerfile"
        - "commands/**/*"
      when: on_success
  needs:
    - job: build
      artifacts: false
  allow_failure: false
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
  script:
    - |
      export APP_NAME="${CI_PROJECT_NAME//_/-}"
      export REPLICAS=1

      echo "Deploying: $CI_PROJECT_NAME"
      export IMAGE_TAG=$IMAGE_TAG
      export NAMESPACE=personal

      envsubst < k8s/deployment.yaml | kubectl apply -f - || exit 1
      #envsubst < k8s/service.yaml | kubectl apply -f - || exit 1
      #envsubst < k8s/configmap.yaml | kubectl apply -f - || exit 1

      kubectl rollout status deployment/$APP_NAME --timeout=60s -n $NAMESPACE || {
        echo "Deployment failed. Events:"
        kubectl get events --sort-by='.metadata.creationTimestamp'
        exit 1
      }
      exit 0


